---

group: stable
dist: trusty
branches:
  only:
    - master

language: python
python: "2.7"

sudo: required
services: docker

env:
  - ANSIBLE_INSTALL_VERSION=1.9.4
  - ANSIBLE_INSTALL_VERSION=2.0.2.0
  - ANSIBLE_INSTALL_VERSION=2.1.1.0

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible==${ANSIBLE_INSTALL_VERSION} ansible-lint
  - pip install virtualenv

script:
  # Setup
  - make travis_test_deps
  - make test_deps
  #Test formatting
  - make lint
  # Test the "build" stage
  - ansible-playbook -i 'localhost,' -c local playbook.yml --tags=build
  - >
    ansible-playbook -i 'localhost,' -c local playbook.yml --tags=build
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # Test the "configure" stage
  - ansible-playbook -i 'localhost,' -c local playbook.yml --tags=configure
  - >
    ansible-playbook -i 'localhost,' -c local playbook.yml --tags=configure
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - ansible-playbook -i 'localhost,' -c local playbook.yml --tags=test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
