---

- name: Create Fabio config
  template:
    dest: "{{ fabio_directories_config }}/fabio.properties"
    src: fabio.properties.j2
  when: fabio_configure
  notify:
    - restart fabio

- name: Start Fabio service
  service:
    state: started
    name: fabio
  when: fabio_manage_service
