---

- name: Download the Go tarball
  get_url:
    url: "https://storage.googleapis.com/golang/{{ fabio_go_pkg }}"
    dest: "/usr/local/src/{{ fabio_go_pkg }}"
    sha256sum: "{{ fabio_go_checksum }}"
    force: no

- name: Extract the Go tarball
  command: "tar -C /usr/local -xf /usr/local/src/{{ fabio_go_pkg }}"
  args:
    creates: /usr/local/go

- name: Download and compile Fabio
  command: "go get github.com/eBay/fabio"
  environment:
    GOPATH: "{{ fabio_directories_install }}"
    PATH: "{{ fabio_directories_install }}/bin:{{ ansible_env.PATH }}:/usr/local/go/bin"
  args:
    chdir: "{{ fabio_directories_install }}"
    creates: "{{ fabio_directories_install }}/bin/fabio"

- name: Link to Fabio binary
  file:
    dest: /usr/bin/fabio
    mode: 731
    src: "{{ fabio_directories_install }}/bin/fabio"
    state: link
